import Foundation
import UIKit
import SwiftUI
import MessageUI
import CoreData

class WishlistSharingService: NSObject, ObservableObject {
    static let shared = WishlistSharingService()
    
    private override init() {
        super.init()
    }
    
    // MARK: - Public Methods
    
    func shareWishlist(_ whiskeys: [Whiskey], completion: @escaping (UIActivityViewController) -> Void) {
        let formattedText = formatWishlistForSharing(whiskeys)
        let activityVC = createActivityViewController(
            text: formattedText,
            subject: "My Whiskey Wishlist"
        )
        completion(activityVC)
    }
    
    func shareReplacements(_ whiskeys: [Whiskey], completion: @escaping (UIActivityViewController) -> Void) {
        let formattedText = formatReplacementsForSharing(whiskeys)
        let activityVC = createActivityViewController(
            text: formattedText,
            subject: "Whiskeys I Want to Replace"
        )
        completion(activityVC)
    }
    
    // MARK: - Private Methods
    
    private func formatWishlistForSharing(_ whiskeys: [Whiskey]) -> String {
        var text = "🥃 My Whiskey Wishlist\n"
        text += "========================\n\n"
        
        if whiskeys.isEmpty {
            text += "No whiskeys on wishlist yet.\n"
            return text
        }
        
        // Group by priority
        let groupedByPriority = Dictionary(grouping: whiskeys) { whiskey in
            Int(whiskey.priority)
        }
        
        let sortedPriorities = groupedByPriority.keys.sorted()
        
        for priority in sortedPriorities {
            let priorityWhiskeys = groupedByPriority[priority] ?? []
            let priorityName = priorityDisplayName(for: priority)
            
            text += "\(priorityName) Priority:\n"
            text += String(repeating: "-", count: priorityName.count + 10) + "\n"
            
            for whiskey in priorityWhiskeys.sorted(by: { ($0.name ?? "") < ($1.name ?? "") }) {
                text += "• \(whiskey.name ?? "Unknown")"
                
                // Add details if available
                var details: [String] = []
                
                if let type = whiskey.type, !type.isEmpty {
                    details.append(type)
                }
                
                if whiskey.proof > 0 {
                    details.append("\(String(format: "%.1f", whiskey.proof))°")
                }
                
                if whiskey.targetPrice > 0 {
                    details.append("$\(Int(whiskey.targetPrice))")
                }
                
                if let distillery = whiskey.distillery, !distillery.isEmpty {
                    details.append("by \(distillery)")
                }
                
                if !details.isEmpty {
                    text += " (\(details.joined(separator: ", ")))"
                }
                
                // Add store information
                if let stores = whiskey.stores?.allObjects as? [Store], !stores.isEmpty {
                    let storeNames = stores.compactMap { $0.name }.sorted()
                    if !storeNames.isEmpty {
                        text += "\n  📍 Available at: \(storeNames.joined(separator: ", "))"
                    }
                }
                
                // Add notes if available
                if let notes = whiskey.whereToFind, !notes.isEmpty {
                    text += "\n  📝 Notes: \(notes)"
                }
                
                text += "\n\n"
            }
        }
        
        text += "Generated by BarrelBook 📱\n"
        text += "Total items: \(whiskeys.count)"
        
        return text
    }
    
    private func formatReplacementsForSharing(_ whiskeys: [Whiskey]) -> String {
        var text = "🔄 Whiskeys I Want to Replace\n"
        text += "==============================\n\n"
        
        if whiskeys.isEmpty {
            text += "No replacement whiskeys listed.\n"
            return text
        }
        
        text += "These are bottles I've enjoyed and want to find again:\n\n"
        
        for whiskey in whiskeys.sorted(by: { ($0.name ?? "") < ($1.name ?? "") }) {
            text += "• \(whiskey.name ?? "Unknown")"
            
            // Add details if available
            var details: [String] = []
            
            if let type = whiskey.type, !type.isEmpty {
                details.append(type)
            }
            
            if whiskey.proof > 0 {
                details.append("\(String(format: "%.1f", whiskey.proof))°")
            }
            
            if let distillery = whiskey.distillery, !distillery.isEmpty {
                details.append("by \(distillery)")
            }
            
            if !details.isEmpty {
                text += " (\(details.joined(separator: ", ")))"
            }
            
            // Add rating if available
            if whiskey.personalRating > 0 {
                let stars = String(repeating: "⭐", count: Int(whiskey.personalRating.rounded()))
                text += "\n  Rating: \(String(format: "%.1f", whiskey.personalRating))/10 \(stars)"
            }
            
            // Add notes if available
            if let notes = whiskey.notes, !notes.isEmpty {
                text += "\n  📝 Notes: \(notes)"
            }
            
            text += "\n\n"
        }
        
        text += "Generated by BarrelBook 📱\n"
        text += "Total items: \(whiskeys.count)"
        
        return text
    }
    
    private func priorityDisplayName(for priority: Int) -> String {
        switch priority {
        case 1: return "🔴 Highest"
        case 2: return "🟠 High"
        case 3: return "🟡 Medium"
        case 4: return "🟢 Low"
        case 5: return "🔵 Lowest"
        default: return "❓ Unknown"
        }
    }
    
    private func createActivityViewController(text: String, subject: String) -> UIActivityViewController {
        let activityItems: [Any] = [text]
        let activityVC = UIActivityViewController(activityItems: activityItems, applicationActivities: nil)
        
        // Configure for email
        activityVC.setValue(subject, forKey: "subject")
        
        // Exclude some activities that don't make sense for this content
        activityVC.excludedActivityTypes = [
            .assignToContact,
            .saveToCameraRoll,
            .addToReadingList,
            .postToFlickr,
            .postToVimeo,
            .postToTencentWeibo,
            .postToWeibo
        ]
        
        return activityVC
    }
}

// MARK: - SwiftUI Integration

struct ShareSheet: UIViewControllerRepresentable {
    let activityViewController: UIActivityViewController
    
    func makeUIViewController(context: Context) -> UIActivityViewController {
        return activityViewController
    }
    
    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {
        // No updates needed
    }
} 